
	<form action="<?php echo $this->url(array('controller'=>'Login','action'=>'index')); ?>" method="post" class="login" title="Faca seu Login">
	
		<label for="usuario">Usuario</label>
		<input type="text" name="usuario" id="usuario" required="required" placeholder="usuario"/>
		
		<label for="senha">Senha</label>
		<input type="password" name="senha" id="senha" required="required"/>
		
		<input type="submit" name="enviar" value="Entrar"/>
		
		
	
	<p><span>Nao sei a senha. :(</span></p>
	</form>

<?php

	?>
