
<div id="menu_estoq">
		<ul>
		  <li><button id="bt_cadCat">Cadastar Categorias</button>  </li>
		  <li><button id="bt_cadProd">Cadastar Produtos</button>  </li>
		  
		</ul>
		
		<ul><button>Visualizar todo Estoque</button></ul>
		
		<ul>Visualiza Por Produto
			
			<li>listar Produtos</li>
		
		</ul>
		
</div>

<div>

Ajax Visualizacao de produto

</div>

<form class="modal" id="cadCat" title="Cadastrar Categoria">
	
	<label for="nome">Nome</label><input id="nome" name="nome"/>
		
</form>

<form class="modal" id="cadProd" title="Cadastrar Produtos">
	
	<label for="nome">Nome</label><input id="nome" name="nome"/>
	<label for="cat">Categoria</label><select><option name="">catProd</select>
	<label for="qtdMin">Minimo</label><input id="qtdMin" name="qtdMin"/>
	
</form>